site_name: "Arcwright Documentation"

site_url: "https://diamondlightsource.github.io/arcwright"

repo_url: "https://github.com/DiamondLightSource/arcwright"

theme:
  name: material

plugins:
- search
- mkdocstrings

nav:
    - 'index.md'
    - 'installation.md'
    - 'tutorial.md'
    - 'arcfai.md'
    - 'contributing.md'
